### ISSUE TITLE
Printer doesn't respond to any commands

### ISSUE THREAD

**Issue by ghost** [bwhmather/python-linemode#1]
I have  TSP100ECO ( TSP143 ) USB StarMicronics star-line mode thermal printer, tried to run your library on Centos 7. My printer is on /dev/usb/lp0, but i tried run all examples, and tests, none of them are succeeded. Tried to disable SELINUX, but still not printing.

Are there any steps to check, where i get wrong ?

p.s with CUPS i could print simple text, but i need STAR LINE mode,

**Comment by bwhmather** [comment]
Try just writing directly to /dev/usb/lp0 (I assume it exists)

echo 'hello world' > /dev/usb/lp0

Should just work if I remember correctly.
I'm afraid I am trapped on my phone for the moment so can't check it myself.

Anything in the system logs?

**Comment by bwhmather** [comment]
Any luck?  Couple of things to check:
- What are the permissions on the printer device file?  You may need to add a rule to udev to set the device up properly when it's plugged in
- Does the printer have a physical switch to change between page mode and line mode?

**Comment by ghost** [comment]
Sorry for late reply. 
1) tried echo 'hello world' > /dev/usb/lp0 - nothing happens
2) all operations done via root privileges
3) TSP100ECO does have 2 DIP switches, but i couldnt find info, what they mean
4) nothing in syslog 

p.s and it still working via cups by executing 
lpr -P Star_TSP100 check.txt

could you say, on what type printer you have tested ?

**Comment by bwhmather** [comment]
I was working with a TSP700II.  Didn't think to check before.  Will update the README.

http://www.starmicronics.com/absolutefm/absolutefm/afmviewfaq.aspx?faqid=244 says that only raster printing is supported by the sample application.  The marketting docs suggest that the printer itself supports line mode through emulation, and there is some very unhelpful [documentation](http://www.starmicronics.com/support/download.aspx?type=5&tabText=StarLine%20Mode%20Command%20Emulator%20Specifications&path=../support/Mannualfolder/comemu_starline_pm.pdf?printerCode=TSP100ECO&id=0) which I guess backs it up.  It would be worth contacting star to ask what the command emulator actually is!

I could also only find mention of one DIP switch for allowing the printer to sleep... Have you tried all the settings anyway?

Are you using the star drivers or were the drivers bundled with cups?  If the latter then the cups source code might be a good place to start trying to figure out how the two printers differ.

**Comment by ghost** [comment]
Hi there! 
A checked again this [link](http://www.starmicronics.com/absolutefm/absolutefm/afmviewfaq.aspx?faqid=244)

Here is written about model **STAR TSP100 ( 143 USB )**  :

> •  The TSP100 Series can only understand raster data (graphical)

So it means, i could only send raster data according to this [manual](http://www.starmicronics.com/support/download.aspx?path=../support/Mannualfolder/star_graphic_cm_en.pdf)  :(

**Comment by bwhmather** [comment]
How on earth did we not find that before.  That's a pitty anyway.  Have you been able to get it working?

**Comment by geftactics** [comment]
For anyone ending up here on the hunt for how they can print from Python to a Star TSP100/143, I've made a Python library that will convert an image into the raster data mentioned above.

You could use `Pillow` to build an image of a receipt, or `imgkit` to build one via HTML, and then process the image with my library.

Hope it helps someone!

https://pypi.org/project/StarTSPImage/
